### ISSUE TITLE
how to encode an set of buffered image to video stream such as h264

### ISSUE THREAD

**Issue by He-Pin** [sarxos/webcam-capture#11]
i grap an set of the buffered image at an fixed time delay,and how can i encode them to an video live stream?current i just render them on an video pannel

**Comment by arminmokri** [comment]
Hello Mr @sarxos
5 years ago i develop video conference program, I used your webcam library.
In my program i get BufferedImage and convert to bytes and send with udp packet it work but need good networks and i did not know anything about codecs but now i start new project i want to use video buffer steam.
