### ISSUE TITLE
Webcam capture in windows 8

### ISSUE THREAD

**Issue by chetL** [sarxos/webcam-capture#111]
The webcam capture works in windows 7 but doesn't work on windows 8. Is there a different version for windows 8?

**Comment by krishna1990fis** [comment]
Hi @sarxos 

I have written a simple java program to capture a image from webcam and store it. and have used your webcam-capture API for that. I have also added all the required JARs mentioned. But i am not able to open my laptop camera for image capture.

Output in my console : 
  `27 [main] INFO com.github.sarxos.webcam.Webcam - WebcamDefaultDriver capture driver will be used
1599 [atomic-processor-1] INFO com.github.sarxos.webcam.ds.cgt.WebcamOpenTask - 
                                                    Opening webcam Integrated Webcam 0
3092 [atomic-processor-1] WARN com.github.sarxos.webcam.ds.buildin.WebcamDefaultDevice - 
Different size obtained vs requested - [176x144] vs [160x120]. Setting correct one. New size is [160x120]
3559 [shutdown-hook-1] INFO com.github.sarxos.webcam.WebcamShutdownHook - 
                                                   Automatic Integrated Webcam 0 deallocation
3559 [shutdown-hook-1] INFO com.github.sarxos.webcam.Webcam - Disposing webcam Integrated Webcam 0`

Thanks,
Krishna P
