### ISSUE TITLE
Error NoClassDefFoundError: org/bridj/cpp/CPPObject

### ISSUE THREAD

**Issue by herrenberger** [sarxos/webcam-capture#114]
Hi sarxos,

first of all: Thank you for your time and effort to develop such a well designed webcam library.

My environment: Ubuntu Linux 13.04 with Netbeans 7.2
The webcam is definately working in applications like Cheese or Skype

I followed exactly the sample code from https://github.com/sarxos/webcam-capture/blob/master/webcam-capture-examples/webcam-capture-executable/src/main/java/com/github/sarxos/webcam/WebcamExecutableExample.java

After compiling and starting I get the following error:

![bildschirmfoto vom 2013-06-21 14_04_41](https://f.cloud.github.com/assets/472658/687136/7a7a579a-da73-11e2-95c4-0eb9446d9758.png)

What went wrong?

Regards, herrenberger

**Comment by uto7** [comment]
Hi sarxos,

https://github.com/sarxos/webcam-capture#download
file:webcam-capture-0.3.11-dist.zip is missing...TT
