### ISSUE TITLE
Dispose Webcam

### ISSUE THREAD

**Issue by rickguise** [sarxos/webcam-capture#121]
Hello. 

I transformed the WebcamViewerExample to a JDialog which is called from a JFrame and works fine until I close and reopen the dialog where the FPS falls to half. Each time I reopen the Dialog, the frames fall some more until the image is very slow. The System.out.println indicates multiple "webcam open" and "webcam closed", for example, the third time I open the JDialog, I get 3 "webcam open". I also tried putting webcam.close() and panel.stop() in the webcamClosed event.

Is this a Dispose problem, I cannot get the webcamDisposed event to fire.

Thanks

**Comment by elduks** [comment]
Hi
please how can i stop the automatic display of webcam activity text from console of eclipse.

Example:
19:15:12.900 [JavaFX Application Thread] INFO  com.github.sarxos.webcam.Webcam - WebcamDefaultDriver capture driver will be used
19:15:12.906 [webcam-discovery-service] DEBUG c.g.s.w.d.b.WebcamDefaultDriver - Searching devices
19:15:13.173 [webcam-discovery-service] DEBUG c.g.s.w.d.b.WebcamDefaultDriver - Found device HP Truevision HD 0
19:15:16.178 [webcam-discovery-service] DEBUG c.g.s.w.d.b.WebcamDefaultDriver - Searching devices
19:15:16.179 [webcam-discovery-service] DEBUG c.g.s.w.d.b.WebcamDefaultDriver - Found device HP Truevision HD 0
19:15:18.880 [AWT-EventQueue-0] DEBUG com.github.sarxos.webcam.WebcamLock - Lock Webcam HP Truevision HD 0
19:15:18.882 [atomic-processor-1] INFO  c.g.s.webcam.ds.cgt.WebcamOpenTask - Opening webcam HP Truevision HD 0
19:15:18.882 [atomic-processor-1] DEBUG c.g.s.w.d.b.WebcamDefaultDevice - Opening webcam device HP Truevision HD 0
19:15:18.882 [atomic-processor-1] DEBUG c.g.s.w.d.b.WebcamDefaultDevice - Webcam device 0 starting session, size java.awt.Dimension[width=176,height=144]
19:15:19.179 [webcam-discovery-service] DEBUG c.g.s.w.d.b.WebcamDefaultDriver - Searching devices
19:15:19.931 [atomic-processor-1] DEBUG c.g.s.w.d.b.WebcamDefaultDevice - Webcam device session started
19:15:19.932 [atomic-processor-1] DEBUG c.g.s.w.d.b.WebcamDefaultDevice - Initialize buffer
19:15:23.179 [atomic-processor-1] DEBUG c.g.s.w.d.b.WebcamDefaultDevice - Webcam device is now open
19:15:23.179 [AWT-EventQueue-0] DEBUG com.github.sarxos.webcam.Webcam - Webcam is now open HP Truevision HD 0
19:15:23.180 [webcam-discovery-service] DEBUG c.g.s.w.d.b.WebcamDefaultDriver - Found device HP Truevision HD 0
19:15:26.181 [webcam-discovery-service] DEBUG c.g.s.w.d.b.WebcamDefaultDriver - Searching devices
19:15:26.182 [webcam-discovery-service] DEBUG c.g.s.w.d.b.WebcamDefaultDriver - Found device HP Truevision HD 0
