### ISSUE TITLE
Report Wrong Code 

### ISSUE THREAD

**Issue by pacozaa** [sarxos/webcam-capture#150]
In DetectMotionExample.java
has some wrong point
at line 18
detector.setCheckInterval(100); // one check per 100 ms
should be
detector.setInterval(100); // one check per 100 ms.
I don't know how it happened but I just check on your document and find the way out.

**Comment by shivapant** [comment]
hii friend ..can you tell me  about motion detection using webcam ,which softwares are use and source code

**Comment by sarxos** [comment]
Hi @shivapant,

Here is very simple implementation:

https://github.com/sarxos/webcam-capture/blob/master/webcam-capture/src/main/java/com/github/sarxos/webcam/WebcamMotionDetector.java

Use case examples:

https://github.com/sarxos/webcam-capture/blob/master/webcam-capture/src/example/java/DetectMotionExample.java

https://github.com/sarxos/webcam-capture/blob/master/webcam-capture/src/example/java/DetectMotionExample2.java

https://github.com/sarxos/webcam-capture/blob/master/webcam-capture/src/example/java/DetectMotionExample3.java
