### ISSUE TITLE
Webcam Not closed even after termination of program

### ISSUE THREAD

**Issue by praveshgupta1993** [sarxos/webcam-capture#159]
``` java
import java.awt.Dimension;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;

import javax.imageio.ImageIO;

import com.github.sarxos.webcam.Webcam;
import com.github.sarxos.webcam.WebcamDevice;


public class Hello {

    public static void main(String[] args) throws IOException {
        Webcam webcam = Webcam.getDefault();
        WebcamDevice device = webcam.getDevice();
        Dimension[] dim = webcam.getViewSizes();
        webcam.setViewSize(dim[2]);
        webcam.open();
        BufferedImage image = webcam.getImage();
        ImageIO.write(image, "PNG", new File("test.png"));
        webcam.close();
        device.dispose();
    }
}
```

Everytime I simply execute code...webcam device does not get closed since I can see the led-light of webcam still on.
Is there something I am missing.

**Comment by monism** [comment]
HI Sarxos,

Webcam webcam = Webcam.getDefault(); **//it opens the java exec a Thread**
		webcam.open();
			ImageIO.write(webcam.getImage(), "PNG",new File("hello2-world.png"));
//     Other statements to get executed

That java exec will remain until i will close the main application , how to close that, as i want close that and execute other statements after that, i don'
<img width="862" alt="webcam" src="https://cloud.githubusercontent.com/assets/7966909/24737564/4d70ec18-1aad-11e7-84d1-9c690028eea1.png">
t want that java exec to remain opened
