### ISSUE TITLE
webcam not being opened for Windows 7, 64-bit

### ISSUE THREAD

**Issue by sscho** [sarxos/webcam-capture#247]
Hello, 

i'm in a bit of a quandary and was hoping you could help me out. I have built a plug-in using the webcam-capture code from OSX 64-bit using netbeans and the code executes flawlessly on my macbook air laptop. Once I export the .jar file onto my windows 7, 64-bit PC, the webcam does not get initialized at all. I have checked that the webcam is set as default on the Windows PC (it is the only video capturing device installed). I have also tested out the webcam (using http://www.testmycam.net/) to make sure the camera stream video from the PC. 

Could you perhaps point me to any other important features of my PC that I should be checking to ensure proper functioning of the webcam?

Thank you.

Shawn

**Comment by anuraagbs** [comment]
hello shawn, were you able to resolve the issue

**Comment by sscho** [comment]
yes, thank you!

**Comment by anuraagbs** [comment]
How did u resolve it, can u let me know
