### ISSUE TITLE
Doubt about Filtering image brightness

### ISSUE THREAD

**Issue by henriquem** [sarxos/webcam-capture#265]
Hi,
I would like to know if is possible I use some Filter to improve the luminance of image captured from Camera IP ?

For example: during the night I need to improve the clarity from Image.
There is support for that ?

Regards

**Comment by JeromeBosman** [comment]
Hello,
Applying the above example with Java 1.8.0_45, image.getType() returns 0, causing the following
> java.lang.IllegalArgumentException: Unknown image type 0
>	at java.awt.image.BufferedImage.<init>(BufferedImage.java:509)
