### ISSUE TITLE
Show image from camera live at Internet, Is possible ?

### ISSUE THREAD

**Issue by henriquem** [sarxos/webcam-capture#280]
Looking the webcam-capture-live-streaming 
I'm thinking if is possible let the images live at Browser captured of Webcam.default() ?

For example:
I created an Jetty embedded in my application java Desktop, I would like to knows  if using the Webcam.default() for capture images live, I transmit 
online, to see this image accessing the address defined in my Jetty embedded, as this: 

``` plain
http://ip:8084/Live Streaming
```

and I could see the images from any place live .

My Jetty embedded is it:

``` java
Server server= new Server(8084);
WebAppContext context = new WebAppContext(server, null,"/");
context.addServlet(new ServletHolder(new LiveStreamingServlet()), "/LiveStreaming");  // LiveStreaming is fake!
server.setHandler(context);
server.start();
server.join();
```

I'm trying to understand it, for implements after.

Thks !

**Comment by sarxos** [comment]
@mcicolella, if you are still interested, here you can find very basic example demonstrating how images feed can be transported to web page over WebSockets.

https://github.com/sarxos/webcam-capture/tree/master/webcam-capture-examples/webcam-capture-websockets
