### ISSUE TITLE
RuntimeException: java.lang.NoclassDefFounderror: com/github/sarxos/webcam/WebcamPanel

### ISSUE THREAD

**Issue by ghost** [sarxos/webcam-capture#281]
Thanks for the good work! I am a java newbie. I want to use the API to display webcam image on a jsp page using java applet, before snapping it.

Once it tries to display the applet picture, it throws an exception RuntimeException: 
java.lang.NoclassDefFounderror: com/github/sarxos/webcam/WebcamPanel.

Please, any idea what I should do will be appreciated,.

Olafimihan

**Comment by afzaalhussain50** [comment]
hi, sarxos i attempt your code of webcam-capture in java applet example, first i get exceptionininitializer error this error is solve by signing all jars then after signing now i get this error RuntimeException: java.lang.NoclassDefFounderror: com/github/sarxos/webcam/WebcamPanel...!!
i am making my degree project live video streaming is my project module, please help me for solving this error, i read your all above comments, but i do not solve this error...

my applet tag is:

<applet codebase ="." code="webcam.WebcamAppletExample.class" archive="webcamStream.jar,webcam-capture-0.3.10.jar,bridj-0.6.2.jar,slf4j-api-1.6.4.jar" width="400" height="450">
                <param name="separate_jvm" value="true" />  
</applet> 
 

and all three jars are in same directory where i have html page...!!

Thanks please help me :(

**Comment by Olafimihan** [comment]
Hi,You could use some javascripts and java code to achieve this. That is what I did eventuaslly.
 Dele Olafimihan

Managing Programmers,
Delaf Systems Coy & Ryte Business Solutions,

Lagos: Suite 6, T&B Plaza,
28, Charity Rd. Abule Egba Lagos.

Abuja: Flat 2, house 13, 
IBB rd, Maitama,
Abuja.
 


     On Saturday, April 18, 2015 3:25 PM, afzaalhussain50 <notifications@github.com> wrote:
   

 hi, sarxos i attempt your code of webcam-capture in java applet example, first i get exceptionininitializer error this error is solve by signing all jars then after signing now i get this error RuntimeException: java.lang.NoclassDefFounderror: com/github/sarxos/webcam/WebcamPanel...!!
i am making my degree project live video streaming is my project module, please help me for solving this error, i read your all above comments, but i do not solve this error...my applet tag is:
 

 and all three jars are in same directory where i have html page...!!Thanks please help me :(—

**Comment by afzaalhussain50** [comment]
thanks for your fast response, can you guide me how i can achieve this, my project module is that a teacher can give online live video lecture using his webcam and multiple students then attend that lecture? 

Thanks

**Comment by sarxos** [comment]
@afzaalhussain50,

IMHO the best option for you will be to pack all these JARs together (webcamStream.jar,webcam-capture-0.3.10.jar,bridj-0.6.2.jar,slf4j-api-1.6.4.jar) in a single archive (aka "shaded" JAR).

Here is a good tutorial of how to shade your code (webcamStream.jar) with the required dependencies (webcam-capture-0.3.10.jar,bridj-0.6.2.jar,slf4j-api-1.6.4.jar):

http://www.mkyong.com/maven/create-a-fat-jar-file-maven-shade-plugin

**Comment by afzaalhussain50** [comment]
@sarxos  thanks for your response, i am not using maven application, can you tell me another best way to create shaded jar with all dependencies , i am using simple java web application in netbeans...!!

Thanks

**Comment by sarxos** [comment]
All the options when you have to shade JARs manually are really not best ways.

In regards to your issue with ```NoClassDefFoundError```, I suppose this is because of the incorrect applet configuration/structure. There is no magic here - Java is telling you that it is not able to locate this specific class in the JARs you pointed out (because of the various reasons - one may be missing, have incorrectly spelled name, etc - all these small things matter).

You wrote:

> all three jars are in same directory where i have html page

But there should be four JARs for your applet, not three.

**Comment by afzaalhussain50** [comment]
thanks @sarxos  i solve my problem by creating single shaded jar :+1: 
can you explain this project how i run this project??
because its video streaming is working but audio is not working? 
https://github.com/ryancheu/webcam-capture/blob/4bd6b8e18cc7b19e8f6776ad2f5f4163053deff8/webcam-capture-examples/webcam-capture-live-streaming/README.md

Thanks

**Comment by sarxos** [comment]
@afzaalhussain50, please find my answer in #335.

**Comment by jeby6372** [comment]
I faced the same issue this morning. Solved it exporting my project 
`menu export/java/Runnable JAR file `
(under eclipse oxygen). 

The worked out jar file can be launch with no problem using 
`java -jar my-project.jar`
