### ISSUE TITLE
Black image captured instead of view from camera

### ISSUE THREAD

**Issue by tiwarigaurav2044** [sarxos/webcam-capture#285]
hey, i am using windows 64 bit and i am trying a simple capture image code but the it unable to capture an image. the captured image is attached
![test](https://cloud.githubusercontent.com/assets/10211583/5458828/7d8b7d42-857b-11e4-8215-0c4d88ef2a56.png)

**Comment by lenikhilsingh** [comment]
Hey iam using windows 10 64 bit ,i have two webcam 1.) inbuild laptop webcam 2.) usb webcam.
my buffered image is fetching black images from my usb webcam, but the same code is working fine with laptop  inbuild webcam. Here's my code
`package library.assistant.ui.addmember;

import com.github.sarxos.webcam.Webcam;
import com.jfoenix.controls.JFXTextField;
import java.awt.Dimension;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.net.URL;
import java.util.ResourceBundle;
import java.util.logging.Level;
import java.util.logging.Logger;
import javafx.embed.swing.SwingFXUtils;
import javafx.event.ActionEvent;
import javafx.fxml.FXML;
import javafx.fxml.Initializable;
import javafx.scene.control.Button;
import javafx.scene.control.Label;
import javafx.scene.control.Tooltip;
import javafx.scene.image.ImageView;
import javafx.scene.image.WritableImage;
import javax.imageio.ImageIO;
import library.assistant.alert.AlertMaker;
import library.assistant.settings.Preferences;



public class WebCamController implements Initializable {
    Webcam webcam;
    Preferences preference= Preferences.getPreferences();
    boolean isRunning = false;

    @FXML
    private ImageView imageHolder;
    @FXML
    private Label displayDir;
    @FXML
    private Button button;
    @FXML
    private JFXTextField id1;
    AlertMaker alert;

    

    @Override
    public void initialize(URL url, ResourceBundle rb) {
        webcam = Webcam.getWebcams().get(0);
        webcam.setViewSize(new Dimension(320,240));
        webcam.open();
        new VideoFeedTaker().start();
        final Tooltip buttonTooltip =new Tooltip();
        buttonTooltip.setText("Capture Image");
        button.setTooltip(buttonTooltip);
        
    }  
    public void setText(String recID){
        this.id1.setText(recID);
        System.out.println("+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++"+id1.getText());
    }
    

    class VideoFeedTaker extends Thread {
        
        @Override
        public void run(){
            while(!isRunning){
                BufferedImage image = webcam.getImage();
                 if(image == null){
                     break;
                 }else{
                    WritableImage image1 = SwingFXUtils.toFXImage(image, null);
                    imageHolder.setImage(image1);
                 }
                try {
                    Thread.sleep(42);
                } catch (InterruptedException ex) {
                    Logger.getLogger(WebCamController.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }

    @FXML
    private void captureImage(ActionEvent event) throws IOException {
        BufferedImage image = webcam.getImage();
        if(image == null){
            System.out.println("this image is null please");
        }else{
            WritableImage image1 = SwingFXUtils.toFXImage(image, null);
            imageHolder.setImage(image1);
        }
        String path = System.getProperty("user.home")+"\\Documents\\camImage\\"+id1.getText()+".jpeg";
        File outputFile = new File(path);
        outputFile.getParentFile().mkdirs();
        ImageIO.write(image, "JPEG", outputFile);
        System.out.println(System.getProperty("user.home"));
        displayDir.setText(path);
        
        if(!isRunning){
            isRunning = true;
            new VideoFeedTaker().start();
        }else{
            isRunning = false;
        }
    }
    
}`
Using javafx and java 8 (IDE netbeans 8.2).
