### ISSUE TITLE
EOF detected, recreating MJPEG stream

### ISSUE THREAD

**Issue by sarxos** [sarxos/webcam-capture#287]
Issue from Omid Haghighatgoo:

---

hi
 I want to use your amazing sarxos project for getting images from an ip camera
I used your sample code like this :

```java
import com.github.sarxos.webcam.Webcam;
import com.github.sarxos.webcam.WebcamPanel;
import com.github.sarxos.webcam.ds.ipcam.IpCamDeviceRegistry;
import com.github.sarxos.webcam.ds.ipcam.IpCamDriver;
import com.github.sarxos.webcam.ds.ipcam.IpCamMode;

import javax.swing.*;
import java.net.MalformedURLException;
import java.net.URL;

/**
 * Created by omid on 12/23/2014.
 */
public class second {

    static {
        Webcam.setDriver(new IpCamDriver());
    }

    public static void main(String[] args) throws MalformedURLException {
        URL url = new URL("http://192.168.1.6");
        IpCamDeviceRegistry.register("WGE-100-CB-5BB9", url, IpCamMode.PUSH);
        WebcamPanel panel = new WebcamPanel(Webcam.getWebcams().get(0));
        //    panel.setFPSLimit(1);
        JFrame f = new JFrame("test");
        f.add(panel);
        f.pack();
        f.setVisible(true);
        f.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }
}
```

and my camera is this :

http://www.brickcom.com/products/DetailView.php?modelname=CB-100Ae

but the result is below message :

```
DEBUG c.g.s.webcam.ds.ipcam.IpCamDevice - EOF detected, recreating MJPEG stream
```

what is the problem ?
I will really appreciate any help

thank you

**Comment by omidhaghighatgoo** [comment]
Thank you very very veeeeeeeeeeeeeeery much
and 
******* HAPPY NEW YEAR *******
I finally find the problem !
the problem was with URL .
each camera has it's own URL that is specific and depends on brand and model
i test these urls for my camera   : 
url = ip address
url = ip address:port
and ...
but none of them was correct
unfortunately  there wasn't any thing on manual or data sheet
finally i found correct camera url on this site : 

http://www.ispyconnect.com/man.aspx?n=Brickcom

**Comment by sarxos** [comment]
Great to hear good news :) I also wish you a Happy New Year! Take care, I'm closing this ticket.

**Comment by betrand** [comment]
Webcam webcam = Webcam.getDefault();
webcam.open();
BufferedImage bufferedImage = webcam.getImage();
LOG.info("BufferedImage", byteBuffer);

I get null printed what can I be doing wrong?

**Comment by sarxos** [comment]
@betrand what is your IP camera URL, are you using JPEG or MJPEG?

**Comment by betrand** [comment]
Thank you.Am on a windows machine with built in Camera. I have tried accessing the camera as belowLOG.info("Webcam name: webcam.getName()");I get Webcam name: Chicony USB 2.0 Camera 0Kind regardsSent from Yahoo Mail for iPadAt 11 Feb 2015 16:13:24, Bartosz Firyn wrote:@betrand what is your IP camera URL, are you using
 JPEG or MJPEG?

**Comment by sarxos** [comment]
@betrand, thank you for clarification. This thread is about EOFs in MJPEG stream, so lets move this discussion to #308 you've created.

**Comment by betrand** [comment]
Hi Bartosz.
It's been a long time I tried your API. Does it support Fingerprint capture and verification now?


Thank you and Kind regards
Betrand Senior Java Architect/DeveloperEMB ERP ConsultantUptitek LtdE-mail:betrandugorji@emb-erp.comSkype: betrandugorji
     

    On Wednesday, 11 February 2015, 16:13, Bartosz Firyn <notifications@github.com> wrote:
 

 @betrand what is your IP camera URL, are you using JPEG or MJPEG?—

**Comment by sarxos** [comment]
Hi @betrand,

Unfortunately I haven't found any way to reliably support finger print images. There is [libfprint-java](https://github.com/phil-lavin/libfprint-java) project, but it seems that not all finger print readers are supported. For example I was unable to use libfprint with a finger print reader embedded in my HP EliteBook ([138a:003c] Validity VFS471 Fingerprint Reader).

However, you may try it out yourself to check if maybe your finger print reader is supported.

**Comment by betrand** [comment]
blockquote, div.yahoo_quoted { margin-left: 0 !important; border-left:1px #715FFA solid !important; padding-left:1ex !important; background-color:white !important; }  I picked up SecuGen fingerprint reader though they have java SDK I thought I should try out your Lib to see if it will detect it as a camera device. If it does then I can go that direction



Sent from Yahoo Mail for iPhone


On Tuesday, August 29, 2017, 13:58, Bartosz Firyn <notifications@github.com> wrote:


Hi @betrand,

Unfortunately I haven't found any way to reliably support finger print images. There is libfprint-java project, but it seems that not all finger print readers are supported. For example I was unable to use libfprint with a finger print reader embedded in my HP EliteBook ([138a:003c] Validity VFS471 Fingerprint Reader).

However, you may try it out yourself to check if maybe your finger print reader is supported.
