### ISSUE TITLE
How Restore connection Camera IP

### ISSUE THREAD

**Issue by henriquem** [sarxos/webcam-capture#291]
Hello, 

I'm trying fix the problem when my network fells,So I didn't get restore the connection with Camera ip, automatic again! 

after that my connection came back, occurs the Exceptions as you see in my issue opened #271 

So, I need to restart my Application again, with the connection guaranteed.

Do you know some solution that while the connection not came back, the Webcam class try reconnect again.
For Example:
Trying connect in 10 seconds  ?

**Comment by sarxos** [comment]
Hi @henriquem,

I post the comment in the previous issue. For now there is no such feature like automatic reconnect, but I think it's very good candidate to be implemented. 

I'm closing this issue. We will communicate in the one you've created earlier :)
