### ISSUE TITLE
[BoofCV]Webcam Straight Line Tracking

### ISSUE THREAD

**Issue by pacozaa** [sarxos/webcam-capture#295]
Hello I just get start on BoofCV. I have to build Line Tracker Robot which use webcam to track the straight line. So which part of the BoofCV website I have to study to achieve my goal. 
Any suggestion would be appriciate.

Thank you.

**Comment by sarxos** [comment]
@pacozaa Sorry, but I'm completely unfamiliar with the BoofCV (I made one commit there just to update old POM dependency), but in regards to features tracking (SIFT, KLT) I can suggest awesome [OpenIMAJ](http://www.openimaj.org) framework.
