### ISSUE TITLE
error in getDefault() method

### ISSUE THREAD

**Issue by aak0012** [sarxos/webcam-capture#297]
hi,
I'm using this api to get pictures from a webcam but when I run the code i get this error

![error](https://cloud.githubusercontent.com/assets/10605245/5809437/525f89d8-9fed-11e4-94c3-af88f800c2fe.png)

and the code is here
http://stackoverflow.com/questions/28019944/github-webcam-caputure-does-not-work

**Comment by sarxos** [comment]
Hi @aak0012,

I tested your code on my PC and it works well, so your stack trace would be helpful here.

**Comment by sarxos** [comment]
@aak0012 any news on this?

**Comment by sarxos** [comment]
@aak0012 I'm closing this ticket due to inactivity and no response for the time.
