### ISSUE TITLE
previous and current BufferedImage references in WebcamMotionEvent 

### ISSUE THREAD

**Issue by krok32** [sarxos/webcam-capture#305]
It would be great if instance of the WebcamMotionEvent contained also references to "previous" and "current" BufferedImage. 
Currently the event listener must call webcam.getImage()  (version 0.3.10)
Or am I missing something?
If it's ok for you, i can fork & make pull request.

**Comment by sarxos** [comment]
Hi @krok32,

You are correct. Such feature would be very helpful in case one would like check the difference between images. Please go ahead and make necessary changes, I will be happy to merge such pull request :)

**Comment by sarxos** [comment]
@krok32, once again than you for this change. I will be closing this ticket.
