### ISSUE TITLE
Please ... Help Me to Extract the finger from noisy binary image

### ISSUE THREAD

**Issue by KuntalAdak** [sarxos/webcam-capture#319]
![binary1-vert](https://cloud.githubusercontent.com/assets/11423042/6595445/67eaee78-c810-11e4-96e1-ffbda961ddf4.jpg)

1. Original Captured Image

2. Binary Image

3. What i want

**Comment by sarxos** [comment]
Hi @KuntalAdak,

Sorry to disappoint you but the image processing and analysis is not a goal of this project. The main goal is to allow Java users to use common API to access webcams, even using various frameworks. Therefore I would like to avoid off-topic questions like this one.

I may be completely wrong, but I would start by interpolate the angle of the image artifacts using two separate, geometrically aligned cameras (not the one), with some fine tuned correction mechanisms (to map artifact placement in image to position on screen). Then, I would incorporate only these artifacts which are observed by these two distinct cameras (position confirmed by angle and distance from camera 1 and 2). Please note that this is just and idea that came into my mind so I can neither give you any ready to use recipe nor I can confirm this method to be actually working in the existing application.
