### ISSUE TITLE
GStreamer error in 64bit windows

### ISSUE THREAD

**Issue by anuraagbs** [sarxos/webcam-capture#324]
Hello,
First of all thanks for the webcam capture driver, I am using GStreamer and it is working like a charm on 32-bit OS,  but when I am using on 64bit, its not working. I do not see any GStreamer installation file  for  64 bit . Can you please help me in resolving this issue.

Thanks,
Anuraag

**Comment by sarxos** [comment]
Hi @anuraagbs,

Unfortunately I found only 32-bit GStreamer installers, no 64-bit ones, however you should be able to w/a this problem by using both 32-bit Java and 32-bit GStreamer installation, thought I never tried such solution.

**Comment by anuraagbs** [comment]
Thank you, will surely try that, appreciate your time

**Comment by sarxos** [comment]
@anuraagbs, please let us know about the outcome :) Take care!

**Comment by anuraagbs** [comment]
Did not work :(

**Comment by sarxos** [comment]
Damn :( In this case I see no possibility to have GStremaer driver running on 64-bit.
