### ISSUE TITLE
Unable to capute HD image.

### ISSUE THREAD

**Issue by goodrahstar** [sarxos/webcam-capture#342]
Hi,
I am trying to capture HD image "HD720" but it shows.
Code:
 webcam.setViewSize(WebcamResolution.HD720.getSize());

Error:
Exception in thread "main" java.lang.IllegalArgumentException: Incorrect dimension [1280x720] possible ones are [176x144] [320x240] [640x480] 
	at com.github.sarxos.webcam.Webcam.setViewSize(Webcam.java:588)
	at WebcamAPI.main(WebcamAPI.java:14)

**Comment by sarxos** [comment]
Hi @goodrahstar,

This example should shed some more light on your problem. Please follow the code and use ```setCustomViewSizes(..)``` method prior the ```setViewSize(..)``` is called.

https://github.com/sarxos/webcam-capture/blob/master/webcam-capture/src/example/java/CustomResolutionExample.java

The "standard" resolutions (in opposite to "custom") are QQVGA, QVGA and VGA, which means that all of them are supported by all manufactured UVC devices (with 99.9% probability). The HD720 is not among them - there is many devices which does not support it.

To cut the story short, to resolve your issue just do:

```java
Dimension[] nonStandardResolutions = new Dimension[] {
	WebcamResolution.HD720.getSize(),
};
Webcam webcam = Webcam.getDefault();
webcam.setCustomViewSizes(nonStandardResolutions);
webcam.setViewSize(WebcamResolution.HD720.getSize());
```

**Comment by goodrahstar** [comment]
Hi @sarxos 
Thanks man for your quick response.
It works :)

**Comment by sarxos** [comment]
Great :) Take care!
