### ISSUE TITLE
WebCam wont start when restarted!!

### ISSUE THREAD

**Issue by TRomesh** [sarxos/webcam-capture#356]
``` java
  public class wc{

     Thread t=new Thread(){
         @Override
          public void run(){
          wCamPanel.start();
         }
        };
     }


private void jLabel15MouseClicked(java.awt.event.MouseEvent evt) {                                      
        InputStream in;

        try{
        File file=new File(String.format("src/Captured-id.jpg",System.currentTimeMillis()));
        ImageIO.write(wcam.getImage(),"JPG",file);
        JOptionPane.showMessageDialog(this,"Image Saved in"+file.getAbsolutePath(),"camcap",1);
        pic.setText(file.getAbsolutePath());      
        picdis.setVisible(false);
        jLabel16.setVisible(true);
        jLabel15.setVisible(false);
      ***  wCamPanel.stop();
      ***  wcam.close();
        WC.t.setDaemon(false);
        WC.t.interrupt(); 
        jLabel16.setIcon(new javax.swing.ImageIcon("src/Captured-id.jpg"));
        in=new FileInputStream(new File("src/camshutter.wav"));
        AudioStream as=new AudioStream(in);
        AudioPlayer.player.start(as);
        }       
        catch(Exception e){
        JOptionPane.showMessageDialog(null, e);
        }

    }                                     
```

**Comment by sarxos** [comment]
I completely do not understand your code. Where is the webcam open? Why are you setting ```setDaemon(true)``` and doing ```interrupt()``` post factum? After the ```start()``` is completed, the thread dies, so why bother setting it to non-daemon and interrupting?

I do not see other important parts of your code, so it's hard to determine why it won't start. Can you please prepare small code example demonstrating the issue you are facing? 

Have you had a chance to take a look at the examples?

https://github.com/sarxos/webcam-capture/blob/master/webcam-capture/src/example/java/TakePictureExample2.java

https://github.com/sarxos/webcam-capture/blob/master/webcam-capture/src/example/java/TakeSnapshotFromVideoExample.java

https://github.com/sarxos/webcam-capture/blob/master/webcam-capture/src/example/java/WebcamViewerExample.java

These may be helpful for you.
