### ISSUE TITLE
Closing webcam

### ISSUE THREAD

**Issue by raaj5671** [sarxos/webcam-capture#371]
Can I know how to close the webcam once i click on the back button in java. Because now I am being shown this error "Exception in thread "AWT-EventQueue-0" java.lang.IllegalStateException: Cannot change resolution when webcam is open, please close it first"

**Comment by sarxos** [comment]
Hi, this can be done simply by calling:

```
webcam.close()
```

**Comment by raaj5671** [comment]
Thanks alot that helped me to solve my problem.
