### ISSUE TITLE
Activate light (flash) of camera

### ISSUE THREAD

**Issue by juanramirezneo** [sarxos/webcam-capture#373]
Hi,
i would like know if is possible activate the light of camera with some java function of library.
Thanks

**Comment by sarxos** [comment]
Hi @juanramirezneo,

Are you referring to:

1. The light diode that indicates that webcam is running, or
2. The extra light source that can be turned on/off?

In case of 1, the light indicator diode is being controlled by hardware and not by the software, so whenever Webcam gets the power, the light turns on, and whenever you shut the power off, the light turns off as well.

In case of 2, no - there is no such possibility.
