### ISSUE TITLE
Osgi dependency on logback should be optional

### ISSUE THREAD

**Issue by schallee** [sarxos/webcam-capture#391]
Greetings, the maven-bundle-plugin is adding logback to the list of imported packages. These should be changed to optional imports as from what I read other places and the code that uses logback, logback is optional.

I'll submit a pull request with this issue once I figure out how.

**Comment by schallee** [comment]
Pull request is #392

**Comment by sarxos** [comment]
Thanks @schallee! Pull request has been merged.
