### ISSUE TITLE
Links to files which are needed for Raspberry Bi are dead

### ISSUE THREAD

**Issue by JuhaMcEla** [sarxos/webcam-capture#405]
These links are dead:
 <a href="https://oss.sonatype.org/service/local/artifact/maven/redirect?r=snapshots&g=com.github.sarxos&a=webcam-capture&v=0.3.11-SNAPSHOT">webcam-capture-0.3.11-SNAPSHOT.jar</a> 
<a href="https://oss.sonatype.org/content/repositories/snapshots/com/github/sarxos/webcam-capture-driver-v4l4j/0.3.11-SNAPSHOT/webcam-capture-driver-v4l4j-0.3.11-20150713.101304-10.jar">webcam-capture-driver-v4l4j-0.3.11-20150713.101304-10.jar</a>

**Comment by sarxos** [comment]
Hi @JuhaMcEla,

0.3.11 is already stable release in Maven Central, so there is no need to use snapshot versions. Check these instead:

* http://search.maven.org/#artifactdetails|com.github.sarxos|webcam-capture|0.3.11|bundle
* http://search.maven.org/#artifactdetails|com.github.sarxos|webcam-capture-driver-v4l4j|0.3.11|jar

_(when you open these links there are JAR files below)_

* http://search.maven.org/remotecontent?filepath=com/github/sarxos/webcam-capture/0.3.11/webcam-capture-0.3.11.jar
* http://search.maven.org/remotecontent?filepath=com/github/sarxos/webcam-capture-driver-v4l4j/0.3.11/webcam-capture-driver-v4l4j-0.3.11.jar

Just FYI, don't forget about dependencies!

**Comment by JuhaMcEla** [comment]
Thank you!
