### ISSUE TITLE
How to retrieve URL linked to an ipcamera?

### ISSUE THREAD

**Issue by mcicolella** [sarxos/webcam-capture#410]
Hi 
is it possibile to retrieve in any way the URL linked to an ipcamera and set into camera.xml?
I can read its name with webcam.getName() but not its URL.
Thanks

**Comment by sarxos** [comment]
Hi @mcicolella,

If you are using only IP camera driver, you may try the following:

```java
Webcam webcam = // ... get webcam instance
WebcamDevice device = webcam.getDevice();
URL url = ((IpCamDevice) device).getURL();
```
