### ISSUE TITLE
May i control the ISO(or gain),expose time settings before i take a picture

### ISSUE THREAD

**Issue by yixblog** [sarxos/webcam-capture#416]
need to do some advanced capture,such as taking pictures of night sky with stars

**Comment by sarxos** [comment]
Hi @yixblog,

This is impossible to be done with Webcam Capture API. You may either switch to C++ and try OpenCV features or stay in Java and use [JavaCV](https://github.com/bytedeco/javacv) (OpenCV bindings for Java), but I never did such things like ISO or gain control and cannot give you any hints on that, but I know that JavaCV and OpenCV interfaces are pretty similar, so this method from should be also available from the Java code:

http://docs.opencv.org/2.4/modules/highgui/doc/reading_and_writing_images_and_video.html#videocapture-set

It allows you to set gain and other camera parameters.
