### ISSUE TITLE
the jar link is broken 

### ISSUE THREAD

**Issue by smilecs** [sarxos/webcam-capture#428]
tried opening the link to the jar but its not live. getting a 404 error. please where else can i get your library

**Comment by sarxos** [comment]
Hi @smilecs, which link, specifically?

**Comment by uto7** [comment]
Hi sarxos,

https://github.com/sarxos/webcam-capture#download
file:**webcam-capture-0.3.11-dist.zip** is missing...TT

**Comment by sarxos** [comment]
Hi @uto7, 

This is now fixed. Thank you for raising this!
