### ISSUE TITLE
How to shutdown the camera?

### ISSUE THREAD

**Issue by Nyutkarsh** [sarxos/webcam-capture#436]
hi, 

I have tried all the method for closing or shutting down the camera but nothing works. Will you please tell me how can close or shut down the camera which is being used.

I want to close it when I click the "X" button on JFrame.
And Same at the time of session time out and Logout.

**Comment by Nyutkarsh** [comment]
@sarxos

**Comment by sarxos** [comment]
@Nyutkarsh, simply do ```webcam.close()``` in your ```windowClosed(WindowEvent e)``` method that comes from ```WindowListener``` interface.

https://docs.oracle.com/javase/tutorial/uiswing/events/windowlistener.html

**Comment by sarxos** [comment]
See this example:

https://github.com/sarxos/webcam-capture/blob/master/webcam-capture/src/example/java/WebcamViewerExample.java

Line 108:

```java
	@Override
	public void windowClosed(WindowEvent e) {
		webcam.close();
	}
```
