### ISSUE TITLE
Missing class - JHFlipFilter

### ISSUE THREAD

**Issue by teamlead-agbaje** [sarxos/webcam-capture#438]
Hi,

In order for me to carry out the right transformation (flipping the picture from the web cam), the example explains that i use the following:

import com.github.sarxos.webcam.util.jh.JHFlipFilter;
private final BufferedImageOp filter = new JHFlipFilter(JHFlipFilter.FLIP_90CW);

However, the class JHFlipFilter does not appear to exist anymore in the webcam library. Is there a new class we should be using? Or is there an additional library I'm to use?

I downloaded the filter library from  jhlabs but that didn't have the JHFlipFilter as well.

Thanks

**Comment by sarxos** [comment]
Use this library:

http://search.maven.org/#artifactdetails|com.jhlabs|filters|2.0.235-1|jar

Here is documentation for ```FlipFilter```:

http://www.jhlabs.com/ip/filters/FlipFilter.html
