### ISSUE TITLE
Driver for MAC 64bits

### ISSUE THREAD

**Issue by diogo10** [sarxos/webcam-capture#439]
Hi there,

I've been trying run with the drives from the main pages, but I didn't get to work. I'd like to test using the mac default webcam. How can I do it?

**Comment by sarxos** [comment]
Which drivers?

**Comment by diogo10** [comment]
I tried JMF and FFmpeg-cli but I guess that I need to install first the drives and then run my code. Is that correct?

**Comment by sarxos** [comment]
Yes. It's correct. There drivers requires software which needs to be installed first. Try running your example without a driver (Webcam Capture it will use refined OpenIMAJ in this case).

**Comment by sarxos** [comment]
@diogo10, I'm closing this one. Please let me know if you have any further issues in regards to this.

**Comment by diogo10** [comment]
Well, didn't work at all. I've tried OpenIMAJ, FFmepg, OpenCV. I will make up the app in Swift, but the windows version I will try to use the library.

**Comment by sarxos** [comment]
Ok, thank you for the info. I should find some newer Mac to perform tests and find out what is wrong. The last time I did it I had 6 years old Mac borrowed from my friend.

**Comment by mjm-cycronix** [comment]
OpenIMAJ works on my 2012 iMac, OS Sierra 10.12.4.  It does spin the CPU 100% no matter how slowly I call getImage(), however.  Suspect still the old bug, reported:
https://github.com/sarxos/webcam-capture/pull/257
