### ISSUE TITLE
D-Link DCS-930 Series Unable to Push MJPEG Due to Content-length Header

### ISSUE THREAD

**Issue by twistedtwin** [sarxos/webcam-capture#440]
The DCS-930 (930, 932 and 934) series all appear to send Content-length instead of Content-Length for the header.  The hack to make is them work is to change the CONTENT_LENGTH constant in IpCamMJPEGStream to "content-length" and then convert the line variable (around line 96 in the same class) to lower case.

**Comment by sarxos** [comment]
Hi @twistedtwin,

This is very nice discovery :) Sorry for a delay in merging your PR - I was pretty busy @ work for the last week and unfortunately missed email notification in regards to this.
