### ISSUE TITLE
Webcam Driver missing

### ISSUE THREAD

**Issue by Sai-Thippasani** [sarxos/webcam-capture#442]
The link provided to webcam-capture-driver-v4l4j-0.3.11-20150713.101304-10.jar in [this ticket](https://github.com/sarxos/webcam-capture/issues/375) is broken. Only version 0.3.10 is available

Can you please fix it?

Thank you

**Comment by sarxos** [comment]
Hi @Sai-Thippasani,

Thank you for the report.

You can find the latest and stable JAR in Maven Central:

http://search.maven.org/#artifactdetails|com.github.sarxos|webcam-capture-driver-v4l4j|0.3.11|jar

Don't forget to add this JAR as well. It's a transitive dependency.

http://search.maven.org/#artifactdetails|com.github.sarxos|v4l4j|0.9.1-r507|jar

Take care!

**Comment by sarxos** [comment]
I've open separate #444 to provide downloadable ZIP bundle for V4L4J and I'm closing this one. Please let me know if you have any further issues.
