### ISSUE TITLE
How to make zoom in and out feature with this lib??

### ISSUE THREAD

**Issue by jeftanathan** [sarxos/webcam-capture#449]
i want to make program with zoom in and out feature.. and i can lock the zoom to my capture image.. how to make it??

sorry for my bad english.. i hope anyone can help my problem.. thanks

**Comment by sarxos** [comment]
Hi @jeftanathan, zooming is not supported by this lib.

**Comment by jeftanathan** [comment]
hmm.. oke... thank you..
