### ISSUE TITLE
No Main manifest in jar file

### ISSUE THREAD

**Issue by BobS0327** [sarxos/webcam-capture#455]
When attempting to execute your jar file...

java -jar webcam-capture-0.3.10.jar 

I get the following message...
no main manifest attribute, in webcam-capture-0.3.10.jar

I'm using Java platform 1.8, Product 1.8.0_91

**Comment by sarxos** [comment]
HI @BobS0327 

You're doing it wrong. This JAR is not executable and it's not a standalone application. It won't run even if you do ```java - jar```. This project is a _library_ which means it gives you classes you need to write your own application which makes use of webcam. Please take a look at the examples for more details.

Some basic examples:

https://github.com/sarxos/webcam-capture/tree/master/webcam-capture/src/example/java

And some more sophisticated ones, to be build with Maven:

https://github.com/sarxos/webcam-capture/tree/master/webcam-capture-examples

**Comment by BobS0327** [comment]
Hello sarxox,
Yea, my bad.  I initially (incorrectly) thought it was an executable jar.
Sorry about that.
Thanx for setting me straight.
Bob
