### ISSUE TITLE
Streaming for Network

### ISSUE THREAD

**Issue by RedToor** [sarxos/webcam-capture#464]
I want do a remote capture cam but I not found example, Client > Program (java) (not websocket) .  thanks

**Comment by sarxos** [comment]
If your remote camera is an IP camera:

https://github.com/sarxos/webcam-capture/tree/master/webcam-capture-drivers/driver-ipcam/src/examples/java

**Comment by RedToor** [comment]
but what is the client and server?

**Comment by djabereddinechabou** [comment]
so u can   can see this project
 https://github.com/sarxos/webcam-capture/tree/master/webcam-capture-examples/webcam-capture-live-streaming it will be very helpfull i tested it on my pc and another  pc and it work very very well

**Comment by RedToor** [comment]
ese proyecto usa librerias portatiles?

**Comment by RedToor** [comment]
solve the problem by taking screenshots and sending them by socket directly, thank you very much for the comments.

**Comment by sarxos** [comment]
Cool! I'm closing this issue.
