### ISSUE TITLE
using snapshot button on the camera usb

### ISSUE THREAD

**Issue by claytonaquino** [sarxos/webcam-capture#466]
how can I take a picture using the snapshot button on the camera usb?
many cameras have this button that allows you take pictures.
http://getusb.info/wp-content/uploads/2007/06/061107a.jpg

**Comment by sarxos** [comment]
Hi @claytonaquino, unfortunately, there is no way to use this button from the Webcam Capture API. However, I do not say it's impossible from Java itself. There is a project called [usb4java](http://usb4java.org/) which theoretically may be used to implement functionality you are looking for. You may try to hack it yourself :)
