### ISSUE TITLE
Wrong JPEG library version: library is 80, caller expects 70

### ISSUE THREAD

**Issue by ertong** [sarxos/webcam-capture#468]
When the library is used in ubuntu 14.04 with javafx, javafx stops loading jpeg images with error:
`Wrong JPEG library version: library is 80, caller expects 70`

To reproduce this issue it is enough to run the following code 
[mavenproject4.TAR.gz](https://github.com/sarxos/webcam-capture/files/284909/mavenproject4.TAR.gz)
using OracleJDK8u92 32bit in ubuntu live cd.

The result should look similar to
![image](https://cloud.githubusercontent.com/assets/4777622/15579882/387ee8d6-236f-11e6-94df-d38d8cb655f8.png)

**Comment by ertong** [comment]
I suspect the issue is linked to the OpenIMAJ library. So I posted it in their tracker too: https://github.com/openimaj/openimaj/issues/105

**Comment by ertong** [comment]
It looks like if we change the initialization sequence, it starts working
```
public class Main  extends Application
{    
    public static void main(String[] args) {
        Application.launch(Main.class, args);
    }
    @Override
    public void start(Stage stage) throws Exception {
        System.out.println("Webcam: "+Webcam.getDefault());
        {
            File f = new File("1.jpg").getAbsoluteFile();
            System.out.println(f.toURI().toString());
            Image image = new Image(f.toURI().toString());
            System.out.println("Image: "+image+" "+image.getWidth()+"x"+image.getHeight()+" Error:"+image.isError()+" "+image.getException());

            Group r = new Group(new ImageView(image));
            Scene s = new Scene(r);
            stage.setScene(s);
        }
        System.out.println("Webcam: "+Webcam.getDefault());
        stage.show();
    }
}
```

It can help as a workaround.

**Comment by sarxos** [comment]
I described this w/a in

https://github.com/sarxos/webcam-capture/wiki/Wrong-JPEG-library-version:-library-is-80,-caller-expects-70

It can be found on the "Known Problems" list on the wiki main:

https://github.com/sarxos/webcam-capture/wiki
