### ISSUE TITLE
Failed to initialize BridJ

### ISSUE THREAD

**Issue by Spenhouet** [sarxos/webcam-capture#470]
I'm trying to get [this project](https://bitbucket.org/Temdegon/greenhouse) running on my Raspberry Pi 3.
It uses this webcam-capture library in version 0.3.9 and bridj 0.6.2 over maven.
I'm using this [USB-Webcam](https://www.amazon.de/CSL-Mikrofon-Lichtsensor-interpoliert-Universal/dp/B00BPBQ2DM/ref=sr_1_1?ie=UTF8&qid=1464191236&sr=8-1&keywords=CSL+-+USB+Webcam+inkl.+Mikrofon+mit+6+LEDs+HD+%2B+Lichtsensor+|+%28interpoliert+12+MP%29).

**When i startup the project i get this exception:**

> OpenJDK Zero VM warning: You have loaded library /tmp/BridJExtractedLibraries1748108788359528428/bridj.so which might have disabled stack guard. The VM will try to fix the stack guard now.
> It's highly recommended that you fix the library with 'execstack -c <libfile>', or link it with '-z noexecstack'.
> java.lang.RuntimeException: Failed to initialize BridJ
> 	at org.bridj.Platform.initLibrary(Platform.java:370)
> 	at org.bridj.Platform.<clinit>(Platform.java:175)
> 	at com.github.sarxos.webcam.ds.buildin.natives.OpenIMAJGrabber.<clinit>(OpenIMAJGrabber.java:59)
> 	at com.github.sarxos.webcam.ds.buildin.WebcamDefaultDriver$WebcamNewGrabberTask.handle(WebcamDefaultDriver.java:44)
> 	at com.github.sarxos.webcam.WebcamProcessor$AtomicProcessor.run(WebcamProcessor.java:56)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
> 	at java.lang.Thread.run(Thread.java:745)
> Caused by: java.lang.UnsatisfiedLinkError: /tmp/BridJExtractedLibraries1748108788359528428/bridj.so: /tmp/BridJExtractedLibraries1748108788359528428/bridj.so: Kann die Shared-Object-Datei nicht öffnen: Datei oder Verzeichnis nicht gefunden
> 	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
> 	at java.lang.ClassLoader.loadLibrary1(ClassLoader.java:1965)
> 	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1890)
> 	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1851)
> 	at java.lang.Runtime.load0(Runtime.java:795)
> 	at java.lang.System.load(System.java:1062)
> 	at org.bridj.Platform.initLibrary(Platform.java:347)
> 	... 7 more
> Exception in thread "atomic-processor" java.lang.UnsatisfiedLinkError: org.bridj.Platform.sizeOf_ptrdiff_t()I
> 	at org.bridj.Platform.sizeOf_ptrdiff_t(Native Method)
> 	at org.bridj.Platform.<clinit>(Platform.java:179)
> 	at com.github.sarxos.webcam.ds.buildin.natives.OpenIMAJGrabber.<clinit>(OpenIMAJGrabber.java:59)
> 	at com.github.sarxos.webcam.ds.buildin.WebcamDefaultDriver$WebcamNewGrabberTask.handle(WebcamDefaultDriver.java:44)
> 	at com.github.sarxos.webcam.WebcamProcessor$AtomicProcessor.run(WebcamProcessor.java:56)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
> 	at java.lang.Thread.run(Thread.java:745)

It seems to come from this library so i thought i'd ask here for help.

_I also wrote an issue for the project [here](https://bitbucket.org/Temdegon/greenhouse/issues/2/how-to-run) but that is more in gernerall on how to get the project running._

**Comment by Spenhouet** [comment]
Okay i solved it.
I changed the webcam-capture version to 0.3.10 and added 

>     <dependency>
>       <groupId>com.nativelibs4java</groupId>
>       <artifactId>bridj</artifactId>
>       <version>0.7.0</version>
>     </dependency>
>     <dependency>
>       <groupId>com.github.sarxos</groupId>
>       <artifactId>webcam-capture-driver-v4l4j</artifactId>
>       <version>0.3.11</version>
>     </dependency>

as well as

>     static {
>         Webcam.setDriver(new V4l4jDriver()); // this is important
>     }

everything as decriped [here](https://github.com/sarxos/webcam-capture/wiki/How-To-Configure-Raspberry-Pi#work-with-classic-uvc-camera)

**Comment by sarxos** [comment]
Cool :) I'm glad you fixed it.

**Comment by danielbathke** [comment]
@Spenhouet, thanks for you question and answer. I run into the same problem, and it fixes.
