### ISSUE TITLE
How to getImage() from Webcam when websocket is not connected?

### ISSUE THREAD

**Issue by sunnyguan** [sarxos/webcam-capture#472]
Hi,

I am currently working on a monitoring system using your Webcam Capture API. It works great but now I am trying to save the images as video AND post them to a websocket if connected. But currently it only save the video when their is a websocket connected. How can I make it so that it will save the images as video when no websocket is connected? I am currently using the websocket example. 

Thanks,
Sunny Guan

**Comment by sarxos** [comment]
Open webcam and start recording in a separate thread and make sure to **not close** webcam after websocket is closed.
