### ISSUE TITLE
Integrate with browser

### ISSUE THREAD

**Issue by timpamungkas** [sarxos/webcam-capture#474]
Hi sarxos, you have an excellent library here. It works fine on swing-based application.
However, can I use webcam-capture at browser, using ZK frameworks?

I'm trying to access client's webcam, but since webcam codes runs on server side, it always take server's webcam.

Thanks

**Comment by sarxos** [comment]
There is no way to use this library in browser without an applet. For webcam integration on web page I recommend https://github.com/jhuckaby/webcamjs

**Comment by alexmao86** [comment]
Using java applet in browser is awful in performance. actually, this is very simple in modern browser with HTML5 support.
You just use one IMG tag with src pointing to one JPEG or some other stream. everything is done.

**Comment by sarxos** [comment]
Yup, exactly. Applets are already dead and if you think about the future of your product you should make your Java application [web start](http://www.oracle.com/technetwork/java/javase/jws-white-paper-150004.pdf) or use HTML5 instead.

**Comment by sarxos** [comment]
Hi guys, I'm closing this ticket since the answer for browser integration question has been already provided.
