### ISSUE TITLE
screen freeze when run(using drag and drag components in netbeans)

### ISSUE THREAD

**Issue by idontwantosleep** [sarxos/webcam-capture#476]

**Comment by sarxos** [comment]
I'm not sure if this is Webcam Capture or NetBeans fault. Can you provide more details?

**Comment by idontwantosleep** [comment]
sirr i got everything working now, thank you so much your work is a
masterpiece and i really appreciate your response btw i add you on facebook
i hope to see you on my timeline so i could follow your works. -greetings
mark

**Comment by sarxos** [comment]
Hi @idontwantosleep, thank you for your feedback. I'm really glad you resolved your problem with the code. Take care! I'm closing this ticket.
