### ISSUE TITLE
Get image delay when the FPS is so slow

### ISSUE THREAD

**Issue by He-Pin** [sarxos/webcam-capture#49]
Hi,sorry for open an new issue again:
When i trying to handle video stream or any other thing,I found an issue that
the call of webcam.getImage()'s returen data just contains an image seconds before
,which means the image is not that real time ,but an old data.
so I want to info that ,could we just take an new snapshot from the webcam but not a little older one?

**Comment by DhanushkaTechnography** [comment]
Is there any way to delay the video feed ?
