### ISSUE TITLE
JavaDocs?

### ISSUE THREAD

**Issue by Arinerron** [sarxos/webcam-capture#517]
I seem to be unable to find the javadocs for sarxos. Mind pointing me in the right direction?

**Comment by sarxos** [comment]
Javadocs for Webcam Capture API? Download javadocs JAR from Maven Central:

http://repo1.maven.org/maven2/com/github/sarxos/webcam-capture/0.3.11/webcam-capture-0.3.11-javadoc.jar

Extract it (e.g. with WinZip, WinRar, unzip, Archive Manager or whatever) and open index.html to read javadocs.

Just FYI, if your IDE is integrated with Maven and you have dependency defined in POM you just need to ctrl-click on class and it will automatically download both javadoc and sources.

![1](https://cloud.githubusercontent.com/assets/472658/21352050/1ac0f98e-c6c0-11e6-96d1-47ddc9b29171.png)

![2](https://cloud.githubusercontent.com/assets/472658/21352061/221683de-c6c0-11e6-9d74-5c032ea11fc8.png)

![3](https://cloud.githubusercontent.com/assets/472658/21352104/50227634-c6c0-11e6-88d2-754c4adcceff.png)
