### ISSUE TITLE
Getting available UVC properties, and setting UVC properties

### ISSUE THREAD

**Issue by justynb** [sarxos/webcam-capture#539]
Is there a way to get the available list of UVC properties for a webcam, and is there a way to set them?

Currently, the webcam-capture library is working perfectly for capturing images, displaying video, etc, but now I'd like to control the exposure of my camera.  What is the correct way of doing this?

**Comment by sarxos** [comment]
Hi @justynb, nope, listing and setting uvc properties is not possible.
