### ISSUE TITLE
WebcamPanel.properties for spanish/spain

### ISSUE THREAD

**Issue by userquin** [sarxos/webcam-capture#549]
WebcamPanel_es_ES.properties

INITIALIZING_DEVICE = inicializando dispositivo
NO_IMAGE = sin imagen
DEVICE_ERROR = error

**Comment by sarxos** [comment]
Thank you @userquin! Added in https://github.com/sarxos/webcam-capture/commit/2044162175b9774d78dc76b4732095d12864d943.
