### ISSUE TITLE
how to change BufferedImage data into ByteBuffer data ?

### ISSUE THREAD

**Issue by turboleee** [sarxos/webcam-capture#554]
I want to make sure the bufferedimage data and the bytebuffer data that I got from the same time ,could you time how to change bufferedimage data I got into bytebuffer ?

**Comment by sarxos** [comment]
The ```BufferedImage``` and ```ByteBuffer``` that you got from ```webcam.getImage()``` and ```webcam.getImageBytes()``` in the same time does not have to and usually will not be the same image. 

To convert ```BufferedImage``` into ```ByteBuffer``` please see: https://stackoverflow.com/questions/29301838/converting-bufferedimage-to-bytebuffer
