### ISSUE TITLE
webcam in JavaFx only(without fxml)

### ISSUE THREAD

**Issue by josephraj2k16** [sarxos/webcam-capture#560]
Dear sarxos,
I want some illustrations regarding opening the webcam in javafx  without using fxml because,I want to build a scalafx application with the code you provide. :-)

**Comment by sarxos** [comment]
Hi @josephraj2k16,

I think you should take a look at this example, prepared by Rakesh Bhatt (@rakeshbhatt10):

https://github.com/sarxos/webcam-capture/tree/master/webcam-capture-examples/webcam-capture-javafx

It demonstrates how to use Webcam Capture API inside JavaFX application without FXML. Scene structure is composed directly in the Java code.
