### ISSUE TITLE
Any code to compare two images??

### ISSUE THREAD

**Issue by josephraj2k16** [sarxos/webcam-capture#561]
Hi sarxos, is there any code to compare two images using their eye coordinates or with something else and return the similarity level?

**Comment by sarxos** [comment]
There is no ready to use code available in this project but you can write your own or use awesome [OpenIMAJ](https://github.com/openimaj/openimaj) framework which is able to detect various image features (eyes, mouth, etc).

Example OpenIMAJ code demonstrating how to per
