### ISSUE TITLE
Error: log4j:WARN No appenders could be found for logger (com.github.sarxos.webcam.Webcam). log4j:WARN Please initialize the log4j system properly.

### ISSUE THREAD

**Issue by Deepanchelliah** [sarxos/webcam-capture#562]
![untitled-1](https://user-images.githubusercontent.com/32704712/31437454-f2fa5ca8-aea2-11e7-931b-aa6f8f968d6a.jpg)

**Comment by Deepanchelliah** [comment]
I was trying to read qr code using webcam, i was getting this error. can you please explain me y am i getting these error. 

https://github.com/sarxos/webcam-capture/tree/master/webcam-capture-examples/webcam-capture-qrcode

**Comment by sarxos** [comment]
This is not error. As stated in a message, this is WARN, which means warning. You get it because you configured your log4j incorrectly. What are your JARs in classpath? If you do not need logs then you can simply ignore this warning and live without it :)

**Comment by sarxos** [comment]
The first result from Google:

https://stackoverflow.com/questions/1140358/how-to-initialize-log4j-properly

https://www.google.com/search?q=log4j%3AWARN+Please+initialize+the+log4j+system+properly.

**Comment by Deepanchelliah** [comment]
Thank you so much :)
