### ISSUE TITLE
Is there any way to switch front/back cameras of laptop (windows).

### ISSUE THREAD

**Issue by amaneer94** [sarxos/webcam-capture#571]
`Webcam webcam = Webcam.getDefault();
webcam.open();
ImageIO.write(webcam.getImage(), "PNG", new File(path));`

when I run this code it is giving streaming from back camera, i want to switch to front camera programatically and vice versa!

**Comment by sarxos** [comment]
The ```Webcam.getDefault()``` return default camera. Did you try ```Webcam.getWebcams()```?

**Comment by amaneer94** [comment]
Yes I tried and it worked.

**Comment by sarxos** [comment]
Cool! I'm closing this issue in this case :) Have fun with your project!
