### ISSUE TITLE
Simplest way to setup / take photo with ip cam?

### ISSUE THREAD

**Issue by Cabusa123** [sarxos/webcam-capture#578]
help?

**Comment by sarxos** [comment]
It depends on model, but the simplest IMO is to call ```wget``` from command line:

```
$ wget "http://{ip.address}/snapshot.cgi?user={username}&pwd={password" -O photo.jpg
```

The {ip.address}, {username} and {password} need to be replaced by a real values, e.g.

```
$ wget "http://192.168.1.23/snapshot.cgi?user=admin&pwd=secret" -O photo.jpg
```

Writing program for this is not the simplest, however, if you insist to do that then take a look at the list of examples in the project [main page](https://github.com/sarxos/webcam-capture#more-examples), for example this one:

https://github.com/sarxos/webcam-capture/blob/master/webcam-capture-drivers/driver-ipcam/src/examples/java/MjpegLignanoBeachExample.java
