### ISSUE TITLE
Cannot set webcam view size in 1280x720

### ISSUE THREAD

**Issue by abv2017** [sarxos/webcam-capture#585]
Please help, I read in the example where you can use a custom view size for the webcam like this:
`webcam.setViewSize(new Dimension(1024, 768));`
But when I use dimensions such as 1280x720, 640x360, even the 1024x768 in the example above, the camera just won't start, no errors or anything, I can use 640x480 though.
My webcam model is Logitech C920, it supports 1280x720 and I want to preview in this resolution.

**Comment by sarxos** [comment]
Did you maybe check a different example where you set non-standard resolution? In case you can't find it (it's on the project [main page](https://github.com/sarxos/webcam-capture)):

https://github.com/sarxos/webcam-capture/blob/master/webcam-capture/src/example/java/CustomResolutionExample.java

In general:

```java
Dimension[] myCustomResolutions = new Dimension[] {
	WebcamResolution.HD.getSize(),
};

Webcam webcam = Webcam.getDefault();
webcam.setCustomViewSizes(myCustomResolutions);
webcam.setViewSize(myCustomResolutions[0]);
```
