### ISSUE TITLE
Autofocus

### ISSUE THREAD

**Issue by saulporras** [sarxos/webcam-capture#590]
Hi,

Is there a way I can turn autofocus off on the webcam?

Thanks.

**Comment by sarxos** [comment]
Nope. There is no such possibility.

**Comment by saulporras** [comment]
Thanks,

By the way great job with this project. It's being very helpful.

Saul.

**Comment by sarxos** [comment]
Thank you @saulporras. Sorry for being unable to help you with this. Good luck!
