### ISSUE TITLE
How to use this WebCam capture on ADF Faces 

### ISSUE THREAD

**Issue by meesawsabba** [sarxos/webcam-capture#611]
Dear Friends,

I am trying to use webcam capture library on ADF Faces page. I have created a Managed bean for this purpose but problem I am having is that how can I add WebcamPanel to my layout?

In JPanel WebcamPanel can be added using  .add() method. How this can be accomplished in ADF Faces ?

Looking forward for your reply.

Regards,

Waseem

**Comment by sarxos** [comment]
Hi @meesawsabba,

Please correct me if I'm wrong - ADF Faces is a JSF technology, yes? And you would like to embed ```WebcamPanel``` in JSF so it's displayed to the user accessing your web page? I have to disappoint you if this is the case - the ```WebcamPanel``` is a Swing component, not JSF, and cannot be used on web page.

Please take a look at [webcamjs](https://github.com/jhuckaby/webcamjs) or [jpeg_camera](https://github.com/amw/jpeg_camera) if you are looking for a technology which can be used on a web page. You may be also interested in [this demo page](https://davidwalsh.name/demo/camera.php) with instructions described [here](https://davidwalsh.name/browser-camera).

**Comment by sarxos** [comment]
I hope the answer I provided is sufficient, thus closing this issue.
