### ISSUE TITLE
Download link for binary is broken

### ISSUE THREAD

**Issue by joepol** [sarxos/webcam-capture#615]

**Comment by yuripourre** [comment]
You are right, the right link should be [https://github.com/sarxos/webcam-capture/archive/webcam-capture-parent-0.3.12.zip](https://github.com/sarxos/webcam-capture/archive/webcam-capture-parent-0.3.12.zip)

I will send a pull request to fix it.

**Comment by joepol** [comment]
Thanks!

**Comment by sarxos** [comment]
Thank you @joepol for pointing this out and @yuripourre for the quick fix :)

**Comment by sarxos** [comment]
@joepol, @yuripourre 

Guys, I just checked the ZIP and the one from Github contains only source code. No dependencies, no docs, etc.

Here is link complete 0.3.12 dist:

http://repo.sarxos.pl/maven2/com/github/sarxos/webcam-capture/0.3.12/webcam-capture-0.3.12-dist.zip

I need to replace the one in Github with this one.

**Comment by sarxos** [comment]
I updated releases page and uploaded missing artifact:

https://github.com/sarxos/webcam-capture/releases/tag/webcam-capture-parent-0.3.12

Also updated README.md to reflect the change.
