### ISSUE TITLE
How can I code Camera in JFrame Form instead of doing it in a class?

### ISSUE THREAD

**Issue by schabab** [sarxos/webcam-capture#625]
@sarxos I dont know how to code it in JFrame Form. Although the webcam preview is okay in the class in your example, but i want to do it in a JFrame Form to make a design for it in my GUI. Please help. I'm using netbeans.
![image](https://user-images.githubusercontent.com/37240517/37241524-78cf80de-2495-11e8-941f-fd800d68e931.png)

**Comment by sarxos** [comment]
Here you can find very basic example: https://github.com/sarxos/webcam-capture/blob/master/webcam-capture/src/example/java/WebcamPanelExample.java
