### ISSUE TITLE
slf4j error

### ISSUE THREAD

**Issue by Nopekick** [sarxos/webcam-capture#643]
<img width="574" alt="screen shot 2018-05-23 at 11 38 35 am" src="https://user-images.githubusercontent.com/33606565/40444303-dbb42606-5e7d-11e8-9247-ccc40e90614b.png">

I get this error when I try to run these lines
<img width="558" alt="screen shot 2018-05-23 at 11 41 36 am" src="https://user-images.githubusercontent.com/33606565/40444438-47473f84-5e7e-11e8-88a0-bf4dfb241351.png">

I see that the webcam momentarily opens when I run the file, but I'm not sure what this error is. I'm using your code via a Maven dependency. Any way to fix the issue?

**Comment by yuripourre** [comment]
This is not an error, it is more like a warning.
You probably didn't include slf4j as dependency, your code will run without issues only the log will be missing.

Your application is closing because you are running webcam.open() without a thread, try to keep your program running.

**Comment by sarxos** [comment]
Hi @Nopekick,

Indeed @yuripourre is correct. This is just a warning. If you include SLF4J-compatible logger in your classpath you should get logs in the console instead of warning. But if you do not want logs then you can simply ignore this warning since it's harmless.

**Comment by ng1905** [comment]
Ignoring a warning message is not really an option in professional applications. Just imagine a CLI based software that gives "warnings" on every start. Users will be confused about it. Is there a way to disable SLF4J alltogether?

**Comment by yuripourre** [comment]
@ng1905, this warning just tells you that slf4j is not included in your application. In my opinion, the easiest way to avoid this warning is to deliver slf4j within your application.

It might include only 15kb to your final jar size.
