### ISSUE TITLE
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder". SLF4J:     Defaulting to no-operation (NOP) logger implementation

### ISSUE THREAD

**Issue by sufyansalim** [sarxos/webcam-capture#647]
Hello I have added all the 3 jars given as a library and tried all the slf4j files given in the link still get this error on itellij idea IDE..

SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Exception in thread "main" java.lang.IllegalArgumentException: image == null!
	at javax.imageio.ImageTypeSpecifier.createFromRenderedImage(ImageTypeSpecifier.java:925)
	at javax.imageio.ImageIO.getWriter(ImageIO.java:1592)
	at javax.imageio.ImageIO.write(ImageIO.java:1520)
	at Main.main(Main.java:14)

**Comment by sufyansalim** [comment]
I have solved it Thank You anyways...

**Comment by ZhongxuanWang** [comment]
> I have solved it Thank You anyways...

Sorry, could you plz share how did you solve it? I met the same problem...

**Comment by sufyansalim** [comment]
It has been a while i will have to check the code if i still have it ,i think it was the issue with the IDE i used eclipse instead of itnellij
