### ISSUE TITLE
zoom in/out camera using webcm-capture

### ISSUE THREAD

**Issue by sachinrke** [sarxos/webcam-capture#660]
hello sir,
first of all, i would like to congratulate you for this wonderful project (Webcam-capture API). you have done grate work. now my issue is that i want to zoom in/out, panning and increase/decrease brightness in IP camera using this (Webcam-Capture API). please help me out to achieve these functionality for the camera...
thank you in advance....

**Comment by sarxos** [comment]
Hi @sachinrke, this unfortunately is not possible with existing Webcam Capture API. If your IP camera expose some kind of REST API which can be used to zoom/pan/tilt then you can try using e.g. [Unirest](http://unirest.io/java.html) to communicate with your IP camera.
