### ISSUE TITLE
Compile time error

### ISSUE THREAD

**Issue by vinodcbe** [sarxos/webcam-capture#69]
Hi i downloaded the jar files you specified and included all the jar files into my project and complied the TestPictureExample. I get an error saying create new class for Webcam. What can i do? Should Actually i complied it using netbeans. Should i have to use another source to run this code?

**Comment by Dejiola** [comment]
Hi, I want my program to take a snapshot using webcam, save it and load the image subsequently. But each time I run the program, the previous image saved is always loaded as the current image cannot be loaded until the project directory is refreshed. I am using eclipse.
