### ISSUE TITLE
Maven compilation fails since https://swt-repo.googlecode.com/svn/repo/ no longer available

### ISSUE THREAD

**Issue by loquagg02** [sarxos/webcam-capture#715]
`mvn clean install -P full `
 fails since https://swt-repo.googlecode.com/svn/repo/ no longer available

Needs to use http://maven-eclipse.github.io/maven

**Comment by loquagg02** [comment]
Change required in webcam-capture-addons/webcam-capture-addon-swt/pom.xml

-      <id>swt-repo</id>
-      <url>https://swt-repo.googlecode.com/svn/repo/</url>
+      <id>maven-eclipse-repo</id>
+      <url>http://maven-eclipse.github.io/maven</url>

**Comment by sarxos** [comment]
Hi @loquagg02,

Thank you for this information. Would you like to send pull request to address this or shall I change it by myself?

**Comment by loquagg02** [comment]
Would you be able to change it yourself?

**Comment by sarxos** [comment]
Ho @loquagg02, this is now addressed in https://github.com/sarxos/webcam-capture/commit/5874815ca3b66423fef0ad430812bb9b0a0506a0. Thank you!
