### ISSUE TITLE
JVM crash after device is disconnected when capture in progress

### ISSUE THREAD

**Issue by raghuramreddy** [sarxos/webcam-capture#75]
Hello Team, the issue which i am going to describe here  is specific to LINUX OS.

I am running the example sample WebcamPanelExample.java

After a long analysis for many hours and debugging the code, i have gathered the below details, as the scenario is not throwing any type of exception to know what is happening.

Go to the method in getImageBytes() in the file WebcamDefaultDevice.java

The following code snippet grabber.nextFrame() which is a native call to the library from java is silently crashing the application in the below scenario, i have tried with many alternatives like calling the above example in a thread with Thread.UncaughtExceptionHandler etc, even it is not showing any stack trace to me regarding the crash.

Please find the scenario where it is getting crashed.

Plug in the USB camera in to any one of the active USB port, now run the above example and observe the video displayed in a frame, now just simply un-plug the USB camera with out closing the video frame, then the JVM exits/crashes silently without throwing any exception in JAVA.

Here what i have observed was, on LINUX whenever the user disconnects the connected USB camera while it is streaming image byte data to the native library then it might be running in to exception and simply shutting down the parent application as well when the parent hits the snippet grabber.nextFrame().

I have fixed this issue in one of the alternative way specific to LINUX

```
boolean flag = false;
Pointer<Byte> image = null;
if(grabber.getVideoDevices().get().asArrayList().size() > 0)
{
           DeviceList list = grabber.getVideoDevices().get();
           for (Device device : list.asArrayList())
           {
                      if(device != null && device.getNameStr().contains(name))
                        {
                                    flag = true;
                                    break;
                         }
           }
           if(flag)
           {
                     grabber.nextFrame();
                     image = grabber.getImage();
           }
}
```

The issue is due to that java is still accessing the  grabber.nextFrame() even in the absence of camera which is disconnected from the machine.

As of now i am preventing the JAVA to access that code in the absence of a specific connected device with which it started interacting.

I have tried with many alternatives to capture the exception, but dint find anything except a blank log, it would be better if the native LIBRARY throws some message to the Java side with which JVM is interacting instead of silently crashing the whole application.

Regards
RAGHU

**Comment by sarxos** [comment]
This issue should be already solved, thus I'm closing this ticket.
