### ISSUE TITLE
java.lang.NoClassDefFoundError: org/slf4j/LoggerFactory in Java Swing SLF4J-simple-1.7.25

### ISSUE THREAD

**Issue by gwynncausing** [sarxos/webcam-capture#768]
Recently when I used Sarxos Camera with 'slf4j-api' but there was an error like this

`SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.`

then it was stated here https://github.com/sarxos/webcam-capture/issues/103 to change it into slf4j-simple and then the next error is this

'java.lang.NoClassDefFoundError: org/slf4j/LoggerFactory'

I am currently doing a personal project in java swing with a camera API

**Comment by sarxos** [comment]
See https://github.com/sarxos/webcam-capture/wiki/java.lang.ClassNotFoundException%3A-org.slf4j.LoggerFactory
