### ISSUE TITLE
How to show s-video and composite video from video capture card in javaFX

### ISSUE THREAD

**Issue by w3farid** [sarxos/webcam-capture#786]
I have created a JavaFX application, this application needs to show composite video and S-Video from the video capture card.
how can I switch the composite video to s-video by JavaFX

**Comment by sarxos** [comment]
Unfortunately I'm not aware of any solution to abstract video capture card as the UVC device. As long as the operating system can abstract hardware device as the [UVC device](https://en.wikipedia.org/wiki/USB_video_device_class) with the ability to capture RGB video frames, the WebcamCapture API should detect it automatically.
