### ISSUE TITLE
Finding USB PORT

### ISSUE THREAD

**Issue by ktrocki** [sarxos/webcam-capture#790]
Hi  @Sarxos,
I am trying to capture information about which ports my external cameras are connected to. I have a physical 6 camera array that I would like to match to my 6 camera live streamed GUI array. All 6 cameras are identical so the following code produces identical names other than the last index.  I believe they are discovered in an arbitrary order as the display order changes run to run. Is there a way to get more information about the webcam (COM Port, Physical Port etc?) so that I can match physical camera location to display location? Thanks!  

Output:
USB2.0 UVC PC Camera 0
USB2.0 UVC PC Camera 1
USB2.0 UVC PC Camera 2
USB2.0 UVC PC Camera 3
USB2.0 UVC PC Camera 4
USB2.0 UVC PC Camera 5

```Webcam.addDiscoveryListener(this);  
picker = new WebcamPicker();  
picker.addItemListener(this);  
List<Webcam> webcams;  
webcams = Webcam.getWebcams();  
for (Webcam webcam : webcams) {  
   System.out.println(webcam.getDevice().getName());  
}
```

**Comment by sarxos** [comment]
This is not possible. The abstraction layer presented to us by operating system prevents us from checking to which port the UVC device is connected to.
