### ISSUE TITLE
Catch the SampleCB error

### ISSUE THREAD

**Issue by Kybox** [sarxos/webcam-capture#796]
Hi !
Could someone tell me how to catch the error from the log :
`ERROR: SampleCB() - buffer sizes do not match`

It's just a System.out.println log and I have no class targeted to understand the error.
It appends when I select the OBS device not launched.

Thanks.

**Comment by alexmao86** [comment]
looks like this is not from java side

**Comment by sarxos** [comment]
Hello there. Yes, it's not from Java. It comes from the underlying native library which uses `videoInput`. The `videoInput` seems to print this error in here:

https://github.com/ofTheo/videoInput/blob/7532fd6ce204ca5e7e7b88c994d453c8831515b9/videoInputSrcAndDemos/libs/videoInput/videoInput.cpp#L189

But it was not updated for ages and I'm not sure how to fix it.

**Comment by Toshimichi0915** [comment]
I'm facing this issue. Has anyone solve this issue?
