### ISSUE TITLE
how to select video input channel when used in video card with more than one input .

### ISSUE THREAD

**Issue by schdai** [sarxos/webcam-capture#801]
Hi, I'm using video capture card to get image from some devices. There are more than one input, including  S-Video, Composite and etc.  Can webCam select input channel？ How？

TKS。

**Comment by alexmao86** [comment]
use WebcamCompositeDriver

**Comment by sarxos** [comment]
@schdai 

The drivers from WebcamCapture project supports only UVC devices and so will not be able to detect cameras connected via S-Video or Composite Cinch, but in general, if you implement (create) custom driver for every input you desire, then you can bundle these drivers together using the `WebcamCompositeDriver` as @alexmao86 suggested.

Just for your information. I never found a Java project to stream video from S-Video or Composite Cinch. I guess you will need some kind of TV tuner for this. Not sure, I never worked with analog video data.
