### ISSUE TITLE
Apply maintainer voluntarily

### ISSUE THREAD

**Issue by alexmao86** [sarxos/webcam-capture#806]
Hi @sarxos ,

I contributed webcam-capture before, I like this project so much. Now I am seeing that lots of issues raised without answers, I have lots of free time, I want to contribute my time to maintain this project, inlcuding:

- answer questions
- base on situation that lots of users are trying to use webcam to Raspberry PI and EE project, I want to enhance underlay JNI JNA for linux and arm
- thinking about springframework integration

I have 14 years of programming focus on Java, C/C++, Python.... both enterprise and embed system.

thanks,

Alex

**Comment by sarxos** [comment]
Hi @alexmao86 

Yes, I do remember your awesome contribution in https://github.com/sarxos/webcam-capture/tree/master/webcam-capture-drivers/driver-raspberrypi.

Thank you for your kind offer. Of course help is highly needed here. I added you as the project contributor. Please contact me at bartoszfiryn@gmail.com to discuss further steps or things you would like to do in the project.

Most important for now would be to clean up the issues. There are many open issues but most of them are actually duplicates of some old problems from the years ago, or enigmatic reports without the code samples which are practically impossible to reproduce. These should be sorted out and closed.
