### ISSUE TITLE
No support on Jetson Nano devices

### ISSUE THREAD

**Issue by akshaykumar123** [sarxos/webcam-capture#812]
java.lang.UnsatisfiedLinkError: /tmp/libs3952141112636090828/libvideo.so: /tmp/libs3952141112636090828/libvideo.so: cannot open shared object file: No such file or directory (Possible cause: can't load AMD 64-bit .so on a AARCH64-bit platform)

webcam-capture : 0.3.10
webcam-capture-driver-v4l4j : 0.3.11
bridj : 0.7.0

**Comment by alexmao86** [comment]
we will evaluate supporting Jatson Nano, since it is popular smart hardware from Nvidia

**Comment by akshaykumar123** [comment]
Hi,

It supports on Jetson nano using fswebcam driver and bridj on classpath

Regards
Akshay Kumar
