### ISSUE TITLE
Exception in thread "main" java.lang.NoClassDefFoundError

### ISSUE THREAD

**Issue by Maruti-Nandan** [sarxos/webcam-capture#828]
I tried to run this code 
```
import com.github.sarxos.webcam.Webcam;
import com.github.sarxos.webcam.WebcamResolution;

import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;

public class cam {
    public static void main(String args[]) throws IOException {
        Webcam webc =Webcam.getDefault();  // Get default camera
        if (webc == null) // Can't find camera
            return;

        webc.close();
        webc.setViewSize(WebcamResolution.VGA.getSize());
        webc.open(); // Open the camera
        try { // save the picture captured
            ImageIO.write(webc.getImage(), "PNG", new File("D:/hello.png"));
        } catch (IOException ioe) {
            ioe.printStackTrace();
        }
        webc.close(); // Close the camera
    }    
}
```

And  got this error:
```
Exception in thread "main" java.lang.NoClassDefFoundError: org/slf4j/LoggerFactory
	at com.github.sarxos.webcam.Webcam.<clinit>(Webcam.java:101)
	at cam.main(cam.java:19)
Caused by: java.lang.ClassNotFoundException: org.slf4j.LoggerFactory
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:602)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 2 more
```
![image](https://user-images.githubusercontent.com/68562256/121771379-a0e2a500-cb8c-11eb-95b0-9af0e62628b1.png)

Please help me to fix this error.

**Comment by sarxos** [comment]
The SLF4J logging framework JAR is missing in your classpath (with other required dependencies as well, e.g. BridJ). See [how to solve missing LoggerFactory class](https://github.com/sarxos/webcam-capture/wiki/How-to-solve-java.lang.ClassNotFoundException:-org.slf4j.LoggerFactory) wiki page for more details on how you can fix it. Please also check the [download](https://github.com/sarxos/webcam-capture#download) section on the main page for the ZIP. In short - you need to have Webcam Capture JAr but also SLF4J and BridJ (or JARs for other capture framework if you are using something non-default).

**Comment by Maruti-Nandan** [comment]
Thanks for replying

**Comment by Maruti-Nandan** [comment]
I added that but now the picture that is captured is totally black.
So, How should I fix that?
