### ISSUE TITLE
How to get a specific USB camera?

### ISSUE THREAD

**Issue by shichiye** [sarxos/webcam-capture#830]
At present, I know that the camera can be obtained by a given name, but I cannot confirm which camera it is. I want to know whether the corresponding USB camera can be obtained by the USB camera similar to the hardware id. I don’t seem to find the corresponding api.

**Comment by sarxos** [comment]
@shichiye 

There is no such API in the Webcam Capture project. What we have here is a very basic abstraction over the UVC device. There is no API to get the USB information. Even if we go into the lower level and dive deep into the native C++ code, there is no such thing as well. The operating system abstracts the device and completely decouples it from the USB transport.

One could in theory use some 3rd party library like [usb4java](http://usb4java.org/) to scan the ports and correlate UVC data from Webcam Capture with the hardware device class present in the USB port, but I never tried this and cannot even tell if such thing is possible. This is just a brief idea that came into my mind.

**Comment by eduramiba** [comment]
I'm working on publishing as open source a native driver capable of providing actual device ids and very good performance. For the moment it will work on Windows only. Maybe tomorrow it's ready, I will reply back.

We use the driver in a production app and works really well.

**Comment by eduramiba** [comment]
Hi,

I just published the driver here: https://github.com/eduramiba/webcam-capture-driver-native

Please let me know if you try it successfully or you have any problem.

To get the device id you will need to cast `WebcamDevice` to `CaptureManagerVideoDevice`

**Comment by shichiye** [comment]
@sarxos @eduramiba Thank you both for your answers.
I will try it, and then I will reply to you @eduramiba

**Comment by pacioc193** [comment]
Could be possible to know the id device of the USB with the relative istance ?

USB\VID_0C45&PID_6366&MI_00\6&183AF011&0&0000

**Comment by eduramiba** [comment]
> Could be possible to know the id device of the USB with the relative istance ?
> 
> USB\VID_0C45&PID_6366&MI_00\6&183AF011&0&0000

Yes, you can with https://github.com/eduramiba/webcam-capture-driver-native and casting `WebcamDevice` to `WebcamDeviceWithId`

**Comment by pacioc193** [comment]
Could you help me with an example in pure Java... I tried to follow the tutorial but after loading the dll no output of which webcam is connected to the computer. Without loading dll everything is working well. i tried to contact you on twitter also.

![image](https://user-images.githubusercontent.com/3874577/145572473-54606439-4d94-4967-94b3-9423ed3775dc.png)
![image](https://user-images.githubusercontent.com/3874577/145572514-00f56b53-a769-4376-b0a3-c740b2a7ce6f.png)

**Comment by pacioc193** [comment]
Also dll are loaded in the project Netbeans as in photo.
![image](https://user-images.githubusercontent.com/3874577/145572697-354b3d55-89d6-4772-8c4e-3259cf75dbb0.png)
I also tried to put in same place where opencv read it's own dll. OpenCv could work well without any issue but this driver won't work....

**Comment by eduramiba** [comment]
@pacioc193 This library tries to load its DLLs from the natives folder relative to where the program is executed. Adding to netbeans or as jar won't do anything.

Please make sure to run your program in a folder where natives is located. Also I recommend setting up a slf4j backend such as logback for viewing logging messages.

**Comment by pacioc193** [comment]
It works. Was a matter of libraries... I'm not using maven project... Standalone application developing here.
Thanks for the support

![image](https://user-images.githubusercontent.com/3874577/145579962-11f92641-14e8-44ba-8ee9-479bf1960ed1.png)

**Comment by eduramiba** [comment]
@pacioc193 Great! 😄

**Comment by pacioc193** [comment]
I think the best ways to solve this issue in the future... release a zip file with all the dependency ahah
