### ISSUE TITLE
Ubuntu: Not able to detect camera

### ISSUE THREAD

**Issue by chottu33** [sarxos/webcam-capture#832]
Hello

 while the recording is on, webcam is not getting connected again, if the camera is disconnected and connected back.
Observation: Discovery Service of the camera is not running
OS: Ubuntu 20, Centos 8
jars version - webcam-capture-0.3.13-20200330.202351-7.jar, bridj-0.7-20140918-2.jar
java version: 1.8.0

**Comment by alexmao86** [comment]
could u please provider hardwaew info?
