### ISSUE TITLE
How to properly kill a thread

### ISSUE THREAD

**Issue by brianmichalk1** [sarxos/webcam-capture#833]
Sometimes my USB glitches while in a getImage() call, which hangs my program.  I've put this into a separate thread and use a semaphore timeout to indicate when getImage() takes too long.  Killing the thread sometimes works but doesn't seem to be the correct approach.  Should I use Webcam.shutdown?

**Comment by alexmao86** [comment]
Hi @brianmichalk1 ,

Java is working at high level, for webcam-capture, it is a lighweight of wrapping of camera accessing via JNA. so device glitch is not handled well well though we introduced WebcamDiscoveryListener.
When you open camera without reset new Driver explicitly, default is:
https://github.com/sarxos/webcam-capture/blob/master/webcam-capture/src/main/java/com/github/sarxos/webcam/ds/buildin/WebcamDefaultDevice.java
https://github.com/sarxos/webcam-capture/blob/master/webcam-capture/src/main/java/com/github/sarxos/webcam/ds/buildin/WebcamDefaultDriver.java

it is thread unsafe and blocking getImage().

My suggestion is:
you can attach a WebcamDiscoveryListener to watch camera devices though it is not fully guaranteed.
manage the getImage() thread gracefully with timeout and WebcamDiscoveryListener
