### ISSUE TITLE
Webcam not working while on Zoom

### ISSUE THREAD

**Issue by cameronboddie** [sarxos/webcam-capture#834]
Hello I have a demo where I need to use the webcam to capture a QR. Simultaneously, I will be on a zoom call with my PM. Is there a way to make this work? It works while not on Zoom but doesn't work even if my camera is off. I haven't been able to properly troubleshoot the issue.

**Comment by alexmao86** [comment]
@cameronboddie underlay camera hardware is an exclusive resource, once you are in Zoom meeting, the camera is taken by Zoom. You can not open it again from another process. at JVM high level, it is hard to debug.

**Comment by cameronboddie** [comment]
Thank you for the quick response. I appreciate it, I'll look into some work arounds for the demo.
