### ISSUE TITLE
Problem with WebcamStreamer start / stop and changing the assigned camera

### ISSUE THREAD

**Issue by stolarek** [sarxos/webcam-capture#839]
Hello everybody,
I use the nice library in my system with multiple cameras. It works just fine. The system takes pictures once a day via the connected cameras. Now to my problem: I want to display the live stream of individual cameras on my settings page and the user should be able to switch between the images of the cameras and align the cameras. I use currently for every webcam one "WebcamStreamer" class with port 8080 + n and switch the livestream with them. After a few minutes of inactivity, the cameras should be switched off. I use WebcamStreamer stop(). Is it possibele to restart an existing Streamer or schould a new object be created?
I tried different combinations but at some point I can't see the livestream.
What is the best way? Is it possible to switch different cameras with just one "WebcamStreamer"?
I would be happy if there are suggestions here.

**Comment by alexmao86** [comment]
Hi @stolarek ,

so sorry to tell you that restart webcam streamer, webcamera API must reallocate stream reading postion again. but this is not implemented, please see comments:

/**
 * This is very simple class which allows video from webcam to be exposed as MJPEG stream on a given
 * port. The mapping between webcam and port is one-to-one, which means that a single port need to
 * be allocated for every webcam you want to stream from.
 *
 * @author Bartoisz Firyn (sarxos)
 */
