### ISSUE TITLE
How to call Webcam.dispose() to release it

### ISSUE THREAD

**Issue by stefan-reich** [sarxos/webcam-capture#848]
Hi,

quick question about your lovely library. I need a way to release the web cam from the current process so another process can access it. (On Linux, only one process can access a webcam at a time.)

The method Webcam.dispose() probably does this. But it's protected, so I don't know how to call it. I could call using reflection but is that necessary?

I also found WebcamDiscoveryService and WebcamDeallocator which indirectly call Webcam.dispose(), but they don't seem suited to what I want to do. I simply want to release a Webcam that I hold a reference to.

Many greetings

**Comment by MrFirekiller** [comment]
It's just webcam.close()

**Comment by stefan-reich** [comment]
Alright that was easy then :)

**Comment by MrFirekiller** [comment]
A good tip is to press the dot before the method name, eg webcam. and then scroll to see all the methods available. It's handy like this. Also see the examples.

**Comment by stefan-reich** [comment]
Yeah that's cute, thanks :) I'm a Java developer since 1998. I was just asking if the webcam is actually released to the OS like this. Could have tested I guess. Greetings

**Comment by MrFirekiller** [comment]
Oh ok I just misunderstood you I guess

**Comment by stefan-reich** [comment]
@MrFirekiller No problem
