### ISSUE TITLE
Not working on Mac m1

### ISSUE THREAD

**Issue by jQrgen** [sarxos/webcam-capture#914]
The library crashed the JVM Desktop mac m1 Kotlin Multiplatform app in runtime.

```
 Failed to initialize BridJ (java.lang.UnsatisfiedLinkError: (...) (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')))
 ``

**Comment by eduramiba** [comment]
I suggest you try to use this driver: https://github.com/eduramiba/webcam-capture-driver-native

**Comment by jQrgen** [comment]
Thanks. Our team has deferred desktop support for webcam so I won't be looking into this any time soon.

**Comment by alexmao86** [comment]
As BridJ stopped maintenance, there are lots of JNI issues of it, we will try to move javacpp as primary JNI solution. thank you for your interests
